
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author enta
 */
public class App extends javax.swing.JFrame {
int idperson = 1;

static  ArrayList<Person> osFormandos = new ArrayList<>();
static  ArrayList<Curso> osCursos = new ArrayList<>();
static  ArrayList<Inscricoes> asInscricoes = new ArrayList<>();
static  ArrayList<Disciplina> asDisciplinas = new ArrayList<>();

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        guardarBt = new javax.swing.JButton();
        restaurarBt = new javax.swing.JButton();
        limparBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        idp = new javax.swing.JTextField();
        listacursos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        atualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nomec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horasc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idc = new javax.swing.JTextField();
        guardarBt1 = new javax.swing.JButton();
        restaurarBt1 = new javax.swing.JButton();
        limparBt1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        res1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        button = new javax.swing.JLabel();
        nomed = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        horasd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        idd = new javax.swing.JTextField();
        guardarBt2 = new javax.swing.JButton();
        restaurarBt2 = new javax.swing.JButton();
        limparBt2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        res2 = new javax.swing.JTextArea();
        listacursos1 = new javax.swing.JComboBox<>();
        atualizar2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        listacursos2 = new javax.swing.JComboBox<>();
        listacursos3 = new javax.swing.JComboBox<>();
        atualizar3 = new javax.swing.JButton();
        atualizar4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        res3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        res4 = new javax.swing.JTextArea();
        listar = new javax.swing.JButton();
        listar1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("País:");

        jLabel1.setText("Nome:");

        jLabel2.setText("Ano:");

        ano.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Altura:");

        altura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        guardarBt.setText("Guardar");
        guardarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtActionPerformed(evt);
            }
        });

        restaurarBt.setText("Restaurar");
        restaurarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarBtActionPerformed(evt);
            }
        });

        limparBt.setText("Limpar");
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });

        res.setColumns(20);
        res.setRows(5);
        jScrollPane1.setViewportView(res);

        jLabel6.setText("ID:");

        idp.setEditable(false);

        listacursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listacursosActionPerformed(evt);
            }
        });

        jLabel9.setText("Curso:");

        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pais)
                                    .addComponent(nome)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(guardarBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restaurarBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limparBt)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listacursos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listacursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(idp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBt)
                    .addComponent(restaurarBt)
                    .addComponent(limparBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aluno", jPanel1);

        jLabel5.setText("Nome:");

        jLabel7.setText("Horas:");

        horasc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("ID:");

        idc.setEditable(false);
        idc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        guardarBt1.setText("Guardar");
        guardarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBt1ActionPerformed(evt);
            }
        });

        restaurarBt1.setText("Restaurar");
        restaurarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarBt1ActionPerformed(evt);
            }
        });

        limparBt1.setText("Limpar");
        limparBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBt1ActionPerformed(evt);
            }
        });

        res1.setColumns(20);
        res1.setRows(5);
        jScrollPane2.setViewportView(res1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomec)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(horasc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guardarBt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaurarBt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparBt1)
                        .addGap(0, 220, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(horasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBt1)
                    .addComponent(restaurarBt1)
                    .addComponent(limparBt1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Curso", jPanel2);

        button.setText("Nome:");

        jLabel10.setText("Horas:");

        horasd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText("ID:");

        idd.setEditable(false);
        idd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        guardarBt2.setText("Guardar");
        guardarBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBt2ActionPerformed(evt);
            }
        });

        restaurarBt2.setText("Restaurar");
        restaurarBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarBt2ActionPerformed(evt);
            }
        });

        limparBt2.setText("Limpar");
        limparBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBt2ActionPerformed(evt);
            }
        });

        res2.setColumns(20);
        res2.setRows(5);
        jScrollPane3.setViewportView(res2);

        listacursos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listacursos1ActionPerformed(evt);
            }
        });

        atualizar2.setText("Atualizar");
        atualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(listacursos1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(atualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomed)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(horasd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(idd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(guardarBt2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(restaurarBt2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(limparBt2)
                            .addGap(210, 210, 210)))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(atualizar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listacursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button)
                        .addComponent(nomed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(horasd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(idd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(61, 61, 61)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardarBt2)
                        .addComponent(restaurarBt2)
                        .addComponent(limparBt2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Disciplina", jPanel3);

        jLabel12.setText("Listar alunos de curso:");

        jLabel13.setText("Listar disciplinas de curso:");

        listacursos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listacursos2ActionPerformed(evt);
            }
        });

        listacursos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listacursos3ActionPerformed(evt);
            }
        });

        atualizar3.setText("Atualizar");
        atualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar3ActionPerformed(evt);
            }
        });

        atualizar4.setText("Atualizar");
        atualizar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar4ActionPerformed(evt);
            }
        });

        res3.setColumns(20);
        res3.setRows(5);
        jScrollPane4.setViewportView(res3);

        res4.setColumns(20);
        res4.setRows(5);
        jScrollPane5.setViewportView(res4);

        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        listar1.setText("Listar");
        listar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(listacursos3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(atualizar4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(listar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(listacursos2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(atualizar3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listacursos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizar3)
                    .addComponent(listar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listacursos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizar4)
                    .addComponent(listar1))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Listar", jPanel4);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void limparBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBt1ActionPerformed
        // TODO add your handling code here:
        nomec.setText("");
        horasc.setText("");
        res1.setText("");
        idc.setText("");

    }//GEN-LAST:event_limparBt1ActionPerformed

    private void restaurarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarBt1ActionPerformed
        // TODO add your handling code here:
        FileInputStream fileInputStream = null;
        Curso subject = null;
        try {
            fileInputStream = new FileInputStream("C:\\Users\\Worten\\AppData\\Local\\Temp\\Curso.txt");
            try (ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream)) {
                osCursos = (ArrayList<Curso>) objectInputStream.readObject();
                subject = (Curso) objectInputStream.readObject();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int x=0; x< osCursos.size(); x++){

                res1.append(String.valueOf(osCursos.get(x) + "\n"));
                nomec.setText(osCursos.get(x).getNomecurso());
                idc.setText(String.valueOf(osCursos.get(x).getIdcurso()));
                // idp.setText(String.valueOf(pessoa.getidperson()));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_restaurarBt1ActionPerformed

    private void guardarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBt1ActionPerformed
        // TODO add your handling code here:
        try {
            Curso curso = new Curso();
            curso.setNomecurso(nomec.getText());
            curso.setHoras(Integer.parseInt(horasc.getText()));
            
            
            int idx = 1;
            for(int x=0; x< osCursos.size(); x++){

                idx++ ;
            }
            curso.setIdcurso(idx);
            idc.setText(String.valueOf(idx));

            osCursos.add(curso);
            res1.setText("");
            for(int x=0; x< osCursos.size(); x++){
                res1.append(String.valueOf("ID Curso: " + osCursos.get(x).getIdcurso()) + " -Nome: " + osCursos.get(x).getNomecurso()+ " -Horas: " + osCursos.get(x).getHoras() +"\n");
            }

            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\Worten\\AppData\\Local\\Temp\\Curso.txt");
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(osCursos);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_guardarBt1ActionPerformed

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
        // TODO add your handling code here:
        pais.setText("");
        nome.setText("");
        ano.setText("");
        altura.setText("");
        res.setText("");
        idp.setText("");
    }//GEN-LAST:event_limparBtActionPerformed

    private void restaurarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarBtActionPerformed
        FileInputStream fileInputStream = null;
        Person pessoa = null;
        try {
            fileInputStream = new FileInputStream("C:\\Users\\Worten\\AppData\\Local\\Temp\\Person.txt");
            try (ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream)) {
                osFormandos = (ArrayList<Person>) objectInputStream.readObject();
                pessoa = (Person) objectInputStream.readObject();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int x=0; x< osFormandos.size(); x++){

                res.append(String.valueOf(osFormandos.get(x) + "\n"));
                pais.setText(osFormandos.get(x).getPais());
                nome.setText(osFormandos.get(x).getNome());
                altura.setText(String.valueOf(osFormandos.get(x).getAltura()));
                ano.setText(String.valueOf(osFormandos.get(x).getAno()));
                idp.setText(String.valueOf(osFormandos.get(x).getidperson()));
                // idp.setText(String.valueOf(pessoa.getidperson()));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_restaurarBtActionPerformed

    private void guardarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtActionPerformed
     
        
            
        
        
        try {
            Person person = new Person();
           
            person.setPais(pais.getText());
            person.setNome(nome.getText());
            person.setAno(Integer.parseInt(ano.getText()));
            person.setAltura(Integer.parseInt(altura.getText()));           
            person.setNomecurso((String) listacursos.getSelectedItem());
            
           
                
                
            int idx = 1;
            for(int x=0; x< osFormandos.size(); x++){

                idx++ ;
            }
            person.setidperson(idx);
            idp.setText(String.valueOf(idx));
           
            osFormandos.add(person);
           
            res.setText("");
            for(int x=0; x< osFormandos.size(); x++){
                res.append(String.valueOf("ID Formando: " + osFormandos.get(x).getidperson()) + " -Nome: " + osFormandos.get(x).getNome() + " - País: " + osFormandos.get(x).getPais()  + " - Inscrito no curso: " + osFormandos.get(x).getNomecurso() + "\n");
            }

            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\Worten\\AppData\\Local\\Temp\\Person.txt");
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(osFormandos);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_guardarBtActionPerformed

    private void guardarBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBt2ActionPerformed
        // TODO add your handling code here:
          try {
            Disciplina disciplina = new Disciplina();
           
            disciplina.setNomedisciplina(nomed.getText());
            disciplina.setHorasdisciplinas(Integer.parseInt(horasd.getText()));        
             disciplina.setNomecurso((String) listacursos1.getSelectedItem());
            
            
            int idx = 1;
            for(int x=0; x< asDisciplinas.size(); x++){

                idx++ ;
            }
            disciplina.setIddisciplina(idx);
            idd.setText(String.valueOf(idx));
           
            asDisciplinas.add(disciplina);
           
            res2.setText("");
            for(int x=0; x< asDisciplinas.size(); x++){
                res2.append(String.valueOf("ID Disciplina: " + asDisciplinas.get(x).getIddisciplina()) + " -Nome: " + asDisciplinas.get(x).getNomedisciplina() + " - Horas: " + asDisciplinas.get(x).getHorasdisciplinas()  +  "- do curso: " + asDisciplinas.get(x).getNomecurso() + "\n");
            }

            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\Worten\\AppData\\Local\\Temp\\Disciplina.txt");
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(asDisciplinas);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_guardarBt2ActionPerformed

    private void restaurarBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarBt2ActionPerformed
        // TODO add your handling code here:
        
         FileInputStream fileInputStream = null;
        Disciplina subject1 = null;
        try {
            fileInputStream = new FileInputStream("C:\\Users\\Worten\\AppData\\Local\\Temp\\Disciplina.txt");
            try (ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream)) {
                asDisciplinas = (ArrayList<Disciplina>) objectInputStream.readObject();
                subject1 = (Disciplina) objectInputStream.readObject();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int x=0; x< asDisciplinas.size(); x++){

                res2.append(String.valueOf(asDisciplinas.get(x) + "\n"));
                nomed.setText(asDisciplinas.get(x).getNomedisciplina());
                horasd.setText(String.valueOf(asDisciplinas.get(x).getHorasdisciplinas()));
                idd.setText(String.valueOf(asDisciplinas.get(x).getIddisciplina()));
                // idp.setText(String.valueOf(pessoa.getidperson()));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_restaurarBt2ActionPerformed

    private void limparBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBt2ActionPerformed
        // TODO add your handling code here:
        nomed.setText("");
        horasd.setText("");
        idd.setText("");
        res2.setText("");
        
        
    }//GEN-LAST:event_limparBt2ActionPerformed

    private void listacursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listacursosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listacursosActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
       
       for(int x=0; x< osCursos.size(); x++){
        listacursos.addItem(osCursos.get(x).getNomecurso());
        } 
        
        
    }//GEN-LAST:event_atualizarActionPerformed

    private void listacursos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listacursos1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_listacursos1ActionPerformed

    private void atualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar2ActionPerformed
        // TODO add your handling code here:
        for(int x=0; x< osCursos.size(); x++){
            listacursos1.addItem(osCursos.get(x).getNomecurso());
        }

    }//GEN-LAST:event_atualizar2ActionPerformed

    private void listacursos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listacursos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listacursos2ActionPerformed

    private void listacursos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listacursos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listacursos3ActionPerformed

    private void atualizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar3ActionPerformed
        // TODO add your handling code here:
         for(int x=0; x< osCursos.size(); x++){
            listacursos2.addItem(osCursos.get(x).getNomecurso());
        }
        
        
        
    }//GEN-LAST:event_atualizar3ActionPerformed

    private void atualizar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar4ActionPerformed
        // TODO add your handling code here:
        
         for(int x=0; x< osCursos.size(); x++){
            listacursos3.addItem(osCursos.get(x).getNomecurso());
        }
    }//GEN-LAST:event_atualizar4ActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        // TODO add your handling code here:
        res3.setText("");
        for (int x = 0; x < osFormandos.size(); x++){
        
        if (String.valueOf(osFormandos.get(x).getNomecurso()).equals(String.valueOf(listacursos2.getSelectedItem()))) {
             
            res3.append(String.valueOf("ID: " + osFormandos.get(x).getidperson() + " Aluno: " + osFormandos.get(x).getNome()) + "\n");
        }
        
        
        }
        
    }//GEN-LAST:event_listarActionPerformed

    private void listar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar1ActionPerformed
        // TODO add your handling code here:
         res4.setText("");
        for (int x = 0; x < asDisciplinas.size(); x++){
        
        if (String.valueOf(asDisciplinas.get(x).getNomecurso()).equals(String.valueOf(listacursos3.getSelectedItem()))) {
             
            res4.append(String.valueOf("ID: " + asDisciplinas.get(x).getIddisciplina()+ " Disciplina: " + asDisciplinas.get(x).getNomedisciplina()) + "\n");
        }
        
        
        }
        
        
        
    }//GEN-LAST:event_listar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField altura;
    private javax.swing.JTextField ano;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton atualizar2;
    private javax.swing.JButton atualizar3;
    private javax.swing.JButton atualizar4;
    private javax.swing.JLabel button;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton guardarBt;
    private javax.swing.JButton guardarBt1;
    private javax.swing.JButton guardarBt2;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField horasc;
    private javax.swing.JTextField horasd;
    private javax.swing.JTextField idc;
    private javax.swing.JTextField idd;
    private javax.swing.JTextField idp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limparBt;
    private javax.swing.JButton limparBt1;
    private javax.swing.JButton limparBt2;
    private javax.swing.JComboBox<String> listacursos;
    private javax.swing.JComboBox<String> listacursos1;
    private javax.swing.JComboBox<String> listacursos2;
    private javax.swing.JComboBox<String> listacursos3;
    private javax.swing.JButton listar;
    private javax.swing.JButton listar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomec;
    private javax.swing.JTextField nomed;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField pais;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JTextArea res;
    private javax.swing.JTextArea res1;
    private javax.swing.JTextArea res2;
    private javax.swing.JTextArea res3;
    private javax.swing.JTextArea res4;
    private javax.swing.JButton restaurarBt;
    private javax.swing.JButton restaurarBt1;
    private javax.swing.JButton restaurarBt2;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    private ListModel<String> teste() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private ListModel<String> teste(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
